name: findik_muhasebe
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mongo_dart: ^0.10.3
  logging: ^1.3.0
  crypto: ^3.0.6
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  http: ^1.2.2
  html: ^0.15.4
  provider: ^6.1.2
  date_time_format: ^2.0.1
  intl: ^0.19.0
  bson: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/login_animation.gif
