name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Flutter SDK'yı belirli bir sürüm ile kur
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'  # 'stable' yerine doğrudan 3.24.2 sürümünü kullanın

      # Bağımlılıkları yükle
      - name: Install dependencies
        run: flutter pub get

      # Testleri çalıştır
      - name: Run tests
        run: flutter test
